In [27]:
import numpy as np 

In [28]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [29]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

#### 1D Array Indexing 

In [32]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
print(a1[0])
print(a1[-1])

0
9


### 2D Array Indexing

In [34]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
print(a2[2,1])

9


In [39]:
print(a2[1,2])

6


In [40]:
print(a2[2,2])

10


In [41]:
print(a2[2,3])

11


In [43]:
print(a2[0,0])

0


In [44]:
print(a2[1,0])

4


### 3D Array Indexing

In [45]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [48]:
print(a3[1,0,1])

5


In [50]:
print(a3[0,1,0])

2


In [51]:
print(a3[0,0,0])

0


In [52]:
print(a3[1,1,0])

6


### 1D Array Slicing

In [53]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a1[2:5]

array([2, 3, 4])

### 2D Array Slicing

In [55]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
a2[0,:]

array([0, 1, 2, 3])

In [58]:
a2[:,2]

array([ 2,  6, 10])

In [62]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [71]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [72]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [74]:
a2[1,0::3]

array([4, 7])

In [80]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

### 3D Array Slicing

In [81]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [84]:
a4 = np.arange(27).reshape(3,3,3)
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [85]:
a4[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [87]:
a4[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [88]:
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [94]:
a4[0,1]

array([3, 4, 5])

In [95]:
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [99]:
a4[1,:,1]

array([10, 13, 16])

In [100]:
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [102]:
a4[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [103]:
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [109]:
a4[0::2,::3,::2]

array([[[ 0,  2]],

       [[18, 20]]])

### Practice Questions On Indexing Slicing On 1D,2D And 3D Array

### 1D Array Indexing And Slicing

In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70])

In [2]:
arr[0]

np.int64(10)

In [3]:
arr[-1]

np.int64(70)

In [4]:
arr[2:6]

array([30, 40, 50, 60])

In [5]:
arr[::2]

array([10, 30, 50, 70])

In [6]:
arr[::-1]

array([70, 60, 50, 40, 30, 20, 10])

In [8]:
arr[1::2]

array([20, 40, 60])

### 2D Array Indexing And Slicing

In [9]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [10]:
# Q1: Get element at row 1, column 2
arr2[1,2]

np.int64(6)

In [11]:
# Q2: Get entire first row
arr2[0]

array([1, 2, 3])

In [12]:
# Q3: Get entire second column
arr2[:,1]

array([2, 5, 8])

In [13]:
# Q4: Get submatrix (first 2 rows, first 2 columns)
arr2[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [14]:
# Q5: Get last row
arr2[-1]

array([7, 8, 9])

In [15]:
# Q6: Get all rows but only last column
arr2[:,2]

array([3, 6, 9])

In [16]:
# Q7: Reverse rows
arr2[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [19]:
# Q8: Reverse columns
arr2[:,::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])