### Indexing

In [1]:
import numpy as np 

In [2]:
arr = np.array([10, 20, 30, 40, 50])

In [6]:
print(arr[0])   # 10
print(arr[-1])  # 50

10
50


In [8]:
# [20,30,40]
arr[1:4] 

array([20, 30, 40])

In [12]:
# [10,20,30]
# arr[0:3] -> gives same result as arr [:3]
arr[:3]

array([10, 20, 30])

In [19]:
# arr [10,30,50]
arr[::2]
# arr[0:5:2] -> gives same result as arr[::2]

array([10, 30, 50])

In [20]:
arr

array([10, 20, 30, 40, 50])

In [21]:
print(arr[[0,2,4]])

[10 30 50]


In [22]:
arr

array([10, 20, 30, 40, 50])

In [23]:
arr[:]

array([10, 20, 30, 40, 50])

In [25]:
arr[:4]

array([10, 20, 30, 40])

In [26]:
arr[1:]

array([20, 30, 40, 50])