### Numpy Basics

In [1]:
import pandas as pd
import numpy as np 

In [8]:
# np.array -> This Creates 1D Array 
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
# type -> gives Type of array
b = np.array([6,7,8,9,10])
print(type(b))

<class 'numpy.ndarray'>


In [13]:
# 2D Array
c = np.array([[1,2,3],[4,5,6]])
print('This is 2D Array:-')
c

This is 2D Array:-


array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# 3D Array
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print('This is 3D Array:-')
d

This is 3D Array:-


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [24]:
# dtype -> convert array into diff data type ex:- float and int 
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [28]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [40]:
# with reshape
np.arange(16).reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [45]:
# np.ones and np.zeros
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
# np.zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
# np.random -> generates random num from 0 to 1
np.random.random((3,3))

array([[0.88210651, 0.39425158, 0.15306303],
       [0.61556837, 0.71247495, 0.88783049],
       [0.6599392 , 0.19806362, 0.65575862]])

In [50]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

### Array Attributes

In [51]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [53]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [54]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [55]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [59]:
# ndim -> tells number of dimensions of array
a1.ndim

1

In [57]:
a2.ndim

2

In [58]:
a3.ndim

3

In [61]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [63]:
# size -> gives total number of elements present inside array
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [64]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### Changing Datatype

In [67]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [68]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [69]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [71]:
# scalar operations
# arithmetic
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [74]:
# relational
a2 >= 15

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [75]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [76]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[21., 76., 89.],
       [63., 36., 91.],
       [62., 62., 17.]])

In [77]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([ 82026., 169632., 137683.])

In [78]:
# mean/median/std/var
np.var(a1,axis=1)

array([868.66666667, 504.22222222, 450.        ])

In [79]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.83665564,  0.56610764,  0.86006941],
       [ 0.1673557 , -0.99177885,  0.10598751],
       [-0.7391807 , -0.7391807 , -0.96139749]])

In [80]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [81]:
# log and exponents
np.exp(a1)

array([[1.31881573e+09, 1.01480039e+33, 4.48961282e+38],
       [2.29378316e+27, 4.31123155e+15, 3.31740010e+39],
       [8.43835667e+26, 8.43835667e+26, 2.41549528e+07]])

In [82]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[35.,  7., 69.],
       [62., 16., 79.]])

### Indexing and Slicing

In [83]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [84]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
a2[1,0]

np.int64(4)

In [87]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [88]:
a3[1,0,1]

np.int64(5)

In [89]:
a3[1,1,0]

np.int64(6)

In [90]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
a1[2:5:2]

array([2, 4])

In [93]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [95]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [96]:
a2[1,::3]

array([4, 7])

In [97]:
a2[0,:]

array([0, 1, 2, 3])

In [98]:
a2[:,2]

array([ 2,  6, 10])

In [99]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [100]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [101]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [102]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [103]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [104]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [105]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [107]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [108]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [109]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [110]:
# reshape

In [112]:
# Transpose -> rows->col , col->row
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [113]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [114]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [115]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [116]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [117]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
np.hsplit(a4,5)

ValueError: array split does not result in an equal division

In [119]:
# vertical splitting

In [120]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [121]:
np.vsplit(a5,2)

ValueError: array split does not result in an equal division