In [1]:
import numpy as np

### np.sort
Return a sorted copy of an array.

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([35, 34, 43, 70, 15, 86, 94, 57, 92, 51, 21, 22, 31, 40, 46],
      dtype=int32)

In [6]:
np.sort(a)

array([15, 21, 22, 31, 34, 35, 40, 43, 46, 51, 57, 70, 86, 92, 94],
      dtype=int32)

In [7]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[50, 69, 98, 61],
       [26, 86, 35, 92],
       [41, 13, 46, 95],
       [ 5, 56,  8, 79],
       [ 3, 49, 12, 50],
       [55, 75, 15,  5]], dtype=int32)

In [10]:
# axis-> 1 is for row and 0 is for column
np.sort(b,axis=1)

array([[50, 61, 69, 98],
       [26, 35, 86, 92],
       [13, 41, 46, 95],
       [ 5,  8, 56, 79],
       [ 3, 12, 49, 50],
       [ 5, 15, 55, 75]], dtype=int32)

### np.append
The numpy.append() appends values along the mentioned axis at the end of the array

In [11]:
a

array([35, 34, 43, 70, 15, 86, 94, 57, 92, 51, 21, 22, 31, 40, 46],
      dtype=int32)

In [12]:
np.append(a,100)

array([ 35,  34,  43,  70,  15,  86,  94,  57,  92,  51,  21,  22,  31,
        40,  46, 100])

In [13]:
b

array([[50, 69, 98, 61],
       [26, 86, 35, 92],
       [41, 13, 46, 95],
       [ 5, 56,  8, 79],
       [ 3, 49, 12, 50],
       [55, 75, 15,  5]], dtype=int32)

In [17]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[50.        , 69.        , 98.        , 61.        ,  0.47489444],
       [26.        , 86.        , 35.        , 92.        ,  0.26920758],
       [41.        , 13.        , 46.        , 95.        ,  0.28296309],
       [ 5.        , 56.        ,  8.        , 79.        ,  0.52394926],
       [ 3.        , 49.        , 12.        , 50.        ,  0.72824935],
       [55.        , 75.        , 15.        ,  5.        ,  0.96623792]])

### np.concatenate
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [18]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [22]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

 ### np.unique
With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [26]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [27]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims
With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

In [28]:
# code
a.shape

(15,)

In [32]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [33]:
np.expand_dims(a,axis=0)

array([[35, 34, 43, 70, 15, 86, 94, 57, 92, 51, 21, 22, 31, 40, 46]],
      dtype=int32)

In [34]:
np.expand_dims(a,axis=1)

array([[35],
       [34],
       [43],
       [70],
       [15],
       [86],
       [94],
       [57],
       [92],
       [51],
       [21],
       [22],
       [31],
       [40],
       [46]], dtype=int32)

### np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [35]:
a

array([35, 34, 43, 70, 15, 86, 94, 57, 92, 51, 21, 22, 31, 40, 46],
      dtype=int32)

In [36]:
# find all indices with value greater than 50
np.where(a>50)

(array([3, 5, 6, 7, 8, 9]),)

In [37]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([35, 34, 43,  0, 15,  0,  0,  0,  0,  0, 21, 22, 31, 40, 46],
      dtype=int32)

In [38]:
np.where(a%2 == 0,0,a)

array([35,  0, 43,  0, 15,  0,  0, 57,  0, 51, 21,  0, 31,  0,  0],
      dtype=int32)

### np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [39]:
a

array([35, 34, 43, 70, 15, 86, 94, 57, 92, 51, 21, 22, 31, 40, 46],
      dtype=int32)

In [42]:
np.argmax(a)

np.int64(6)

In [43]:
b

array([[50, 69, 98, 61],
       [26, 86, 35, 92],
       [41, 13, 46, 95],
       [ 5, 56,  8, 79],
       [ 3, 49, 12, 50],
       [55, 75, 15,  5]], dtype=int32)

In [44]:
# Column wise max index values
np.argmax(b,axis=1) 

array([2, 3, 3, 3, 3, 1])

In [45]:
# Row wise max index values
np.argmax(b,axis=0) 

array([5, 1, 0, 2])

In [46]:
# similarly argmin for finding minimum value
# np.argmin
np.argmin(a)

np.int64(4)

### np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [50]:
a1 =np.array([1,2,3,4,5,6,7,8,9,10])
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
a1.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [53]:
b

array([[50, 69, 98, 61],
       [26, 86, 35, 92],
       [41, 13, 46, 95],
       [ 5, 56,  8, 79],
       [ 3, 49, 12, 50],
       [55, 75, 15,  5]], dtype=int32)

In [54]:
b.cumsum()

array([  50,  119,  217,  278,  304,  390,  425,  517,  558,  571,  617,
        712,  717,  773,  781,  860,  863,  912,  924,  974, 1029, 1104,
       1119, 1124])

In [55]:
# Similarly there is # np.cumprod for finding production values

### np.corrcoef
Return Pearson product-moment correlation coefficients.

In [56]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [57]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin
With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [58]:
a

array([35, 34, 43, 70, 15, 86, 94, 57, 92, 51, 21, 22, 31, 40, 46],
      dtype=int32)

In [62]:
items = [10,35,60,50,40,77,85]
a[np.isin(a,items)]

array([35, 40], dtype=int32)

### np.flip
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [63]:
a

array([35, 34, 43, 70, 15, 86, 94, 57, 92, 51, 21, 22, 31, 40, 46],
      dtype=int32)

In [64]:
np.flip(a)

array([46, 40, 31, 22, 21, 51, 92, 57, 94, 86, 15, 70, 43, 34, 35],
      dtype=int32)

In [65]:
b

array([[50, 69, 98, 61],
       [26, 86, 35, 92],
       [41, 13, 46, 95],
       [ 5, 56,  8, 79],
       [ 3, 49, 12, 50],
       [55, 75, 15,  5]], dtype=int32)

In [66]:
np.flip(b,axis=1)

array([[61, 98, 69, 50],
       [92, 35, 86, 26],
       [95, 46, 13, 41],
       [79,  8, 56,  5],
       [50, 12, 49,  3],
       [ 5, 15, 75, 55]], dtype=int32)